import {ApiProperty} from "@nestjs/swagger";
import {IsOptional, IsString} from "class-validator";

export class UserLoginDto {
  @ApiProperty({
    description: "The encoded cryptographic signature generated by the user’s wallet.",
    example:
      "0x354b2d913bd02d1da38902358b92606fdc98d4af40a5a7e407d6ba259fc5b33c20a8c95115bade01e09d75ecf59d1bd789ae2219f965db819102a646d545dd2f1b"
  })
  @IsString()
  encodedSignature: string;

  @ApiProperty({
    description: `The SIWE (Sign-In With Ethereum) message signed by the user's wallet. 
    This message includes user details, terms, and other metadata like domain, address, nonce, and issuedAt timestamp.`,
    example: `{\"domain\":\"localhost:3000\",\"address\":\"0x48a24df2a67b11C23e1ec15750f815F178a4D7Ae\",\"statement\":\"Hello, Welcome\\n1. Users must be 13 years or older to use this service.\\n2. Users agree not to post any abusive, offensive, or illegal content.\\n3. Users are responsible for the security of their own account.\\n4. The service provider reserves the right to remove any content or suspend accounts as needed.\\n5. Users agree to respect the privacy and rights of other users.\\n6. This request will not trigger a blockchain transaction or cost any fees.\",\"uri\":\"http://localhost:3000\",\"version\":\"1\",\"chainId\":8453,\"nonce\":\"VdyrflaxzVhcMzQFs\",\"issuedAt\":\"2024-05-05T15:57:45.480Z\"}`
  })
  @IsString()
  siweMessage: string;
}
