import { IsString, IsNotEmpty } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";

export class VerifySignatureDto {
    @ApiProperty({
        description: "The message that was signed by the wallet",
        example: "This is a sample message",
    })
    @IsString()
    @IsNotEmpty()
    message: string;

    @ApiProperty({
        description: "The signature generated by signing the message",
        example: "0x5b6b9c9... (signature)",
    })
    @IsString()
    @IsNotEmpty()
    signature: string;

    @ApiProperty({
        description: "The Ethereum address of the signer",
        example: "0xAbC123... (Ethereum address)",
    })
    @IsString()
    @IsNotEmpty()
    address: string;
}
