import * as Joi from "joi";

export const validationSchema = Joi.object({
    APP_PORT: Joi.number().default(3000),
    APP_NAME: Joi.string().default("Gloop"),
    APP_DESCRIPTION: Joi.string().default("Gloop API"),
    APP_VERSION: Joi.string().default("1.0.0"),
    APP_IS_PRODUCTION: Joi.boolean().default(false),
    DATABASE_HOST: Joi.string().required(),
    DATABASE_PORT: Joi.number().required(),
    DATABASE_USER: Joi.string().required(),
    DATABASE_PASSWORD: Joi.string().required(),
    DATABASE_NAME: Joi.string().required(),
    JWT_SECRET: Joi.string().default("secret"),
    JWT_ACCESS_TOKEN_TIME: Joi.string().default("2h"),
    JWT_REFRESH_TOKEN_TIME: Joi.string().default("7d"),
    NETWORK: Joi.string().required(),
    CONTRACT_ADDRESS_TESTNET: Joi.string().required(),
    CONTRACT_ADDRESS_MAINNET: Joi.string().required(),
    TESTNET_RPC_SOCKET: Joi.string().required(),
    TESTNET_RPC_URL: Joi.string().required(),
    MAINNET_RPC_SOCKET: Joi.string().required(),
    MAINNET_RPC_URL: Joi.string().required(),
    GM_POINTS_CONTACT_ADDRESS_TESTNET: Joi.string().required(),
    GM_POINTS_CONTACT_ADDRESS_MAINNET: Joi.string().required(),
    GM_BTC_TESTNET: Joi.string().required(),
    GM_ETH_TESTNET: Joi.string().required(),
    GM_SOL_TESTNET: Joi.string().required(),
    USDC_TESTNET: Joi.string().required(),
    GM_BTC_MAINNET: Joi.string().required(),
    GM_ETH_MAINNET: Joi.string().required(),
    GM_SOL_MAINNET: Joi.string().required(),
    USDC_MAINNET: Joi.string().required(),
});
